a = int(input('digite um valor:'))
b = int(input('digite outro valor:'))
s = (a + b)
m = (a * b)
d = (a / b)
di = (a // b)
e = (a ** b)
print('A soma é {}, o produto é {} e a divisão é {}'.format(s, m, d), end=' ')
print('Divisão inteira {} e Potência {}'.format(di, e))
