n = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(n))
print('É alfanumérico?', n.isalnum())
print('É alfabético?', n.isalpha())
print('É numérico?', n.isnumeric())
print('Está em minúsculas?', n.islower())
print('Está em maiúsculas?', n.isupper())
print('Está capitalizada?', n.istitle())
