n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
n3 = int(input('Digite mais um número: '))
a = (sorted((n1, n2, n3)))
print('O maior número é {}'.format(max(a)))
print('O menor número é {}'.format(min(a)))